### PR TITLE
Add Arnaud Legoux Moving Average indicator & tests

### PR DESCRIPTION
**Pull request by johanhenriksson**
I've implemented the [Arnaud Legoux Moving Average](http://www.arnaudlegoux.com/img/ALMA-Arnaud-Legoux-Moving-Average.pdf) and added some test cases. I've tried to optimize it but I'm not an expert in C so please review the code.

I personally use the node bindings for tulip indicators and would like to use this specific indicator there. Created this pull request in case it's something you would like to add to the library, otherwise I will probably maintain a private fork of this repo + node bindings for my own use.

Notes:
* I could not get the TCL scripts to run so I did my best to add the indicator manually, but it's also added to the scripts so that it should (hopefully) be properly added if run by somone else
* Perhaps add a new error code for malloc errors. 
* Perhaps I should use the buffer utility struct instead of allocating manually

Thanks for the cool library!

### CODE REVIEW

**Comment by codeplea** [comment]
Thanks for this! I'll try to look into it soon and get back to you.

Where did you take the unit-test numbers in `extra.txt` from? Do you know if there are any example calculations provided by Legoux?

**Comment by johanhenriksson** [comment]
Cool!

I couldn't find much test data so I shamelessly stole them from another project 😬

Actually checked one of the numbers by hand too, it was terribly tedious but correct!

On 1 Mar 2018, at 16:17, Lewis Van Winkle <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for this! I'll try to look into it soon and get back to you.

Where did you take the unit-test numbers in extra.txt from? Do you know if there are any example calculations provided by Legoux?

**Comment by codeplea** [comment]
It seems that www.arnaudlegoux.com has gone offline.

Luckily, the wayback machine has it.

Website: https://web.archive.org/web/20180328151041/http://www.arnaudlegoux.com:80/
PDF: https://web.archive.org/web/20180328151041/http://www.arnaudlegoux.com:80/img/ALMA-Arnaud-Legoux-Moving-Average.pdf

**Comment by johanhenriksson** [comment]
I see. I think I have a copy of the original C# code as well if you need it. Anyways any news on merging this? :) I'm using your library for node.js so it would be cool if this implementation eventually made its way there!

Thanks

**Comment by codeplea** [comment]
@johanhenriksson Yes, I very much want to merge this, and release it with version 0.9. I sent you an email yesterday regarding the CA signoff. Did you not get it? Could you email me and I will resend?

**Comment by codeplea** [comment]
Got it! Thanks!

My plan is to release 0.9 early next year. Hopefully we'll have about a dozen new indicators.

**Pull request merged**
