### PR TITLE
Recursive Moving Trend Average indicator

### PR DESCRIPTION
**Pull request by rdbuf**
The source is [*Dennis Meyers. The Japanese Yen, Recursed, 1998*](https://meyersanalytics.com/publications2/jyrecursed.pdf)

rmta-1

### CODE REVIEW

**Comment by codeplea** [comment]
Thanks for this. It is interesting. Where did you get the numbers for the test suite (extra.txt) from?

**Comment by rdbuf** [comment]
Unfortunately the author does not provide the numbers, so I’ve had do handcraft them using Excel.

I’ve been validating it as well against existing implementations such as https://www.tradingview.com/script/TTYuhwQN-Recursive-Moving-Trend-Average/ and found that the numbers diverge a bit. I’m currently investigating it and will update on this as soon as I find the reason.

**Comment by rdbuf** [comment]
The problem was due to the recurrent nature of the formula. It was crucial to use a large dataset so as to eliminate the approximation error.

Currently, the test case uses the data on AAPL for the past year and compares the results with those produced by the implementation referenced above. One could achieve even better results using a larger dataset.

**Comment by codeplea** [comment]
Thanks for your work. This looks pretty good, and I will likely merge it into the 0.9 release. However, it'll be a couple weeks before I have time to really dig in and give a proper review.

**Comment by rdbuf** [comment]
I do not provide a ref version just because there are no nontrivial optimizations involved that'd obscure the formulas. The formulas, however, are quite complex. Currently, the implementation matches [this tradingview script](https://www.tradingview.com/script/TTYuhwQN-Recursive-Moving-Trend-Average/), and I will make corrections in case you point on a mistake.

**Pull request merged**
