### PR TITLE
Use CMake for building [WIP]

### PR DESCRIPTION
**Pull request by rdbuf**
Currently, we build with a gnumake script. It causes a race condition at code generation stage. I don't think it worth it to waste time trying to come up with a fix; rather, I propose using a cmake script that causes a lot less problems.

Code generation happens at the configuration stage, i.e. when doing `cmake ..`.

`benchmark.c` is currently unsupported.

A lot of ideas were borrowed from #27.

### CODE REVIEW

**Comment by codeplea** [comment]
I don't see the benefit of this, but there are a lot of drawbacks.

1. It's an extra dependency.
2. It's another thing to maintain.
3. It obscures what's actually happening.
4. It's an extra thing to go wrong.
5. You're missing `benchmark` and `tiamalgamation`, so it's incomplete.

>build with a gnumake script. It causes a race condition at code generation stage. 

I just tweaked the Makefile a bit, maybe it'll work better for you now. If you're still having problems with it, I'm sure we can fix it.

**Comment by rdbuf** [comment]
Well, yes, your updated Makefile seems to be doing its work properly. However, in case anything breaks again, I'm not sure I'll be able to fix it as I'm not that proficient in gnumake.

Therefore, I'm leaving the updated CMakeLists here as it can potentially benefit someone. Both `benchmark` and `benchmark2` are supported now, and `tiamalgamation.c` is halfway done.

**Comment by codeplea** [comment]
Could we use CMake with AppVeyor to build with MSVC on Windows?

**Comment by rdbuf** [comment]
Technically it should be so, as soon as MSVC is able to compile the project - when I tried to use VS to build it, the only thing that went wrong was usage of VLA in CE implementation, which is not strictly necessary.

**Comment by rdbuf** [comment]
Just built 0.9 with this config. Problems occured:
- talib dependency of `benchmark.c` is a problem, this target should be made optional (since it's not the primary target of any newcomer building the lib, and `benchmark2.c` accomplishes pretty much the same thing)
- `file(CREATE_LINK ...)` is unavailable until 3.14.1, needs a workaround

**Comment by rdbuf** [comment]
Changes compared to the previous version:
- rebased onto `benchmark2`
- handled the necessary flags for MSVC
- build as a shared lib (with the possibility of turning back to static with a simple switch)
- set the proper `WORKING_DIRECTORY` instead of creating a symlink to  `tests/`
- `benchmark`, which depends on talib, is made optional (though currently it's considered a test failure if the binary is absent - needs a further investigation)

**Comment by rdbuf** [comment]
Also, `-ffast-math` and `-march=native` enabled in release mode, and various sanitizers in debug mode.

**Comment by rdbuf** [comment]
What's planned is to enable profile guided optimizations for each target platform

**Pull request closed without merging**
