### PR TITLE
Relative Momentum Index indicator

### PR DESCRIPTION
**Pull request by rdbuf**
The source is:
- *Relative Momentum Index: Modifying RSI by Roger Altman, Stocks and Commodities, Feb '93*
- *Robert W. Colby. The Encyclopedia of Technical Market Indicators, p. 610* - for RSI

Screenshot from 2019-04-22 10-34-57

Please note that this is not compatible with the RSI present in the library because that implementation in its turn not compatible with the EMA present in the library. I stick to the `ema.c` approach.

### CODE REVIEW

**Comment by codeplea** [comment]
We really need tests for every indicator.

**Comment by chromafunk** [comment]
Is there something I'm missing, or the RSI is not correct ? I can't get the same values as the tradingview RSI

**Comment by codeplea** [comment]
@chromafunk This PR is about RMI, not RSI.

**Comment by chromafunk** [comment]
sorry, my mistake

**Pull request merged**
