### PR TITLE
Acceleration Bands indicator

### PR DESCRIPTION
**Pull request by rdbuf**
The source is *Price Headley. Big Trends In Trading, 2002, p. 92* (can be found on google books):

abands-1

### CODE REVIEW

**Comment by codeplea** [comment]
What are your sources for the algorithm?

>Test case borrowed from Lean

What is Lean?

**Comment by codeplea** [comment]
The output names should have the indicator name in them. Instead of {upper_band lower_band basis}, {abands_upper abands_lower abands_basis} might be better.

**Comment by joshuaulrich** [comment]
> What is Lean?

I assume it's referring to [QuantConnect's Trading Engine](https://github.com/QuantConnect/Lean).

**Comment by rdbuf** [comment]
Yes, that's correct.

**Comment by rdbuf** [comment]
Updated the PR.
- specified the source
- added a reference implementation
- changed output names
- achieved an x2 speedup

**Pull request merged**
